# Generated by Django 5.0.6 on 2024-06-16 17:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=255)),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(999999)])),
                ('gender', models.CharField(choices=[('M', 'M'), ('F', 'F')], max_length=1)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999999)])),
                ('address', models.CharField(max_length=255)),
                ('booking_date', models.DateField()),
                ('booking_time', models.TimeField()),
                ('booking_status', models.CharField(max_length=20)),
                ('payment_status', models.CharField(max_length=20)),
                ('payment_method', models.CharField(max_length=20)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payment_amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99999)])),
                ('service', models.TextField()),
            ],
        ),
    ]
